### ISSUE TITLE
Cron reports: Exception in thread Thread-1 (most likely raised during interpreter shutdown)

### ISSUE THREAD

**Issue by myfirstnameispaul** [piwik/piwik-log-analytics#75]
I have been getting the following in my Cron reports for a very long time now:

> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
>   File "/usr/lib/python2.7/threading.py", line 504, in run
>   File ".../piwik/misc/log-analytics/import_logs.py", line 1472, in _run_bulk
>   File "/usr/lib/python2.7/Queue.py", line 168, in get
>   File "/usr/lib/python2.7/threading.py", line 236, in wait
> \<type 'exceptions.TypeError'>: 'NoneType' object is not callable

Ubuntu 12.04.5 server x64 running PHP 5.5.25, nginx 1.8.0, MariaDB 5.5.43 and Piwik 2.13.1 is installed.

**Comment by diosmosis** [comment]
This looks like a CPython issue (as in, not directly related to the log importer). Can you provide some details about how you are using the log importer? Does it run continually? Does the error occur after importing is finished? Also what minor version of python are you using (ie, 2.7.???)?

**Comment by myfirstnameispaul** [comment]
The script runs during postrotate of the daily log rotation:

    .../piwik/misc/log-analytics/import_logs.py --url=https://www.example.com/piwik .../access.log.1 --idsite=7 --enable-reverse-dns --exclude-path=/w/* --exclude-path=/blog/* --exclude-path=/piwik/* --exclude-path=/forums/* --recorders=1 --enable-reverse-dns

Python is 2.7.3, just the vanilla of whatever comes with Ubuntu Precise.

**Comment by diosmosis** [comment]
Can you tell if the error is reported after the logs are done importing? If you can verify this is the case for each error, then it occurs when the log importer is shutting down, and can be safely ignored (ie, it won't interfere w/ the actual importing).

I will look into the stack trace to see if the error can be avoided w/o switching python implementations.

**Comment by myfirstnameispaul** [comment]
The same message reports that the script successfully imported the records, and I can see the records in the Piwik reports. It doesn't seem to effect operation any, just an email I get every day.
 
There is an additional error message that I did not include because it began at the same time that the build I use for nginx changed something relating to the upstart, so other errors related to logrotation and nginx (where I have the piwik script) have been occurring, whereas the error I reported above has been going on since I discovered my mail queues weren't being processed over a year ago, so I can't say exactly how long this error has been going on, but at least over one year.

Here is the additional error message:

> In order for your logs to be processed by Piwik, you may need to run the following command:
> ./console core:archive --force-all-websites --force-all-periods=315576000 --force-date-last-n=1000 --url='https://www.example.com/piwik'

I have run `$ php ../piwik/console core:archive --force-all-websites --force-all-periods=315576000 --force-date-last-n=1000 --url='https://www.example.com/piwik'` and it completed successfully, but changed nothing.

**Comment by diosmosis** [comment]
That is not an error message, just a note. If you import visits in the past, the 'archiving' process has to be invoked. How you do this (or if you actually need to) depends on how you configured your Piwik. It's not related to the python error in your original message.

After some investigation, I believe I can commit a quick fix for this issue.

**Comment by diosmosis** [comment]
@myfirstnameispaul I believe I've fixed the issue, you can get the updated import_logs.py script here: https://raw.githubusercontent.com/piwik/piwik-log-analytics/master/import_logs.py

I can't reproduce the error, so if it reoccurs for you, please comment here.

**Comment by myfirstnameispaul** [comment]
Looks like that has the effect of changing the message:

> Exception in thread Thread-1 (most likely raised during interpreter shutdown):
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
>   File "/usr/lib/python2.7/threading.py", line 504, in run
>   File "/var/www/unpm.org/public/piwik/misc/log-analytics/import_logs.py", line 1475, in _run_bulk
>  \<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'info'

**Comment by diosmosis** [comment]
@myfirstnameispaul can you comment the line at 1475 in import_logs.py and tell me if it fixes the issue or if another error crops up?

**Comment by myfirstnameispaul** [comment]
I commented out line 1475. 1474, 1475,1476 now:

                except:
    #                logging.info("Queue does not exist anymore, exception details: " + sys.exc_info()[0])
                    return

I will let you know what happens after tonight's rotation.

**Comment by myfirstnameispaul** [comment]
It looks like all of the error messages are gone and Piwik is successfully importing the records.

Is there any way to determine why I still get this message:

> In order for your logs to be processed by Piwik, you may need to run the following command:
./console core:archive --force-all-websites --force-all-periods=315576000 --force-date-last-n=1000 --url='https://www.example.com/piwik'

**Comment by diosmosis** [comment]
It's hard coded. Like I said before, it's not an error. It's there to reduce support requests.

**Comment by myfirstnameispaul** [comment]
In 2.14 and 2.14.1 I have commented line 1479 to remove the exception report from cron reports email.

**Comment by diosmosis** [comment]
I removed the line in master, shouldn't happen when you update again.
